### ISSUE TITLE
C99 for loop initial declarations and compilation errors (Ubuntu 14.04 and Win 8.1)

### ISSUE THREAD

**Issue by Disane** [rednaga/yara-python#1]
Hi there!

I think I'm going to ask a similar question as I did in the case of CalebFenton/dex-oracle xD (Failing to install and use code, my bad)

So, I tried to run python setup.py install on yara-python and it started compiling yara-python modules.
The problem is that after building a couple of object files I ran into several of these issues:

```
yara/libyara/modules/dex.c:519:3: note: use option -std=c99 or -std=gnu99 to compile your code
yara/libyara/modules/dex.c: In function ‘get_prototype_string’:
yara/libyara/modules/dex.c:557:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < type_list_size; i++) {
```

where an initializer was used inside a for loop. Which should be fine since this 
doesn't violate the C/C++ syntax. But for some reason I get this error. Maybe the build instructions weren't correct?

I also tried installing the whole thing on Windows where Visual Studio 9.0 was used to compile the modules but it exited with the following error:

```
...
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Iyara/libyara/include -Iyara/libyara/ -I. -IC:\Python27\include -IC:\Python27\PC /Tcyara-python.c /Fobuild\temp.win32-2.7\Release\yara-python.obj
yara-python.c
c:\python27\include\pyconfig.h(68) : fatal error C1083: Cannot open include file: 'io.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe' failed with exit status 2
```

Hopefully these error messages will help.

Regards,
Disane

**Comment by Disane** [comment]
Problem solved: basically you need a newer version of Ubuntu that can run a newer version of GCC/G++. Meh, I guess If I wanted, to I could've gotten everything up to date on the old 14.04 but, I got lazy (who wants to deal with that many errors?) and installed a new VM instead.

**Comment by strazzere** [comment]
Glad you where able to solve the issues. I'll look into the C99 initialization issue shortly.
