### ISSUE TITLE
openssl/md5.h installation error

### ISSUE THREAD

**Issue by hexrom** [rednaga/yara-python#3]
Still getting this error, I tried export CFLAGS='-I/usr/local/Cellar/openssl/1.0.21/include' how do I get around this error? 

1 warning generated.
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DHAVE_MEMMEM=1 -DHASH_MODULE=1 -Iyara/libyara/include -Iyara/libyara/ -I. -I/opt/local/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c yara/libyara/modules/hash.c -o build/temp.macosx-10.11-intel-2.7/yara/libyara/modules/hash.o
yara/libyara/modules/hash.c:30:10: fatal error: 'openssl/md5.h' file not found
#include <openssl/md5.h>
         ^
1 error generated.
error: command 'cc' failed with exit status 1

**Comment by strazzere** [comment]
You should disable the module which is using this, or link your openssl includes to the installer.
